<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vb</string>
	</array>
	<key>name</key>
	<string>VB.NET</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment-single-quote</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-rem</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-a</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-c</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-d</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-e</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-f</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-g</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-h</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-i</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-j</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-k</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-l</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-m</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-n</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-o</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-p</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-r</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-s</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-t</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-u</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-v</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-w</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-x</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-y</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#integer-literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#floating-point-literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#character-literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string-literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#date-literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#symbol</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifier</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>character-literal</key>
		<dict>
			<key>comment</key>
			<string>char literals</string>
			<key>match</key>
			<string>(?i:["\x{201C}\x{201D}]([^"\x{201C}\x{201D}]|["\x{201C}\x{201D}]{2})["\x{201C}\x{201D}]C)</string>
			<key>name</key>
			<string>string.quoted.double.vbnet</string>
		</dict>
		<key>comment-rem</key>
		<dict>
			<key>comment</key>
			<string>comments REM</string>
			<key>match</key>
			<string>(?i)(?&lt;=[^_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Nd}\p{Mn}\p{Mc}\p{Cf}\p{Pc}])REM((?=[\r|\n])| [^\r\n]*)</string>
			<key>name</key>
			<string>comment.line.singlequote.vbnet</string>
		</dict>
		<key>comment-single-quote</key>
		<dict>
			<key>comment</key>
			<string>comments single-quote</string>
			<key>match</key>
			<string>['\x{2018}\x{2019}][^\r\n]*</string>
			<key>name</key>
			<string>comment.line.singlequote.vbnet</string>
		</dict>
		<key>date-literal</key>
		<dict>
			<key>comment</key>
			<string>date literals</string>
			<key>match</key>
			<string>(#\s*(((((\d+/\d+/\d+)|(\d+-\d+-\d+))\s+(\d+:\d+(:\d+)?\s*(AM|PM)?)))|((\d+/\d+/\d+)|(\d+-\d+-\d+))|(\d+:\d+(:\d+)?\s*(AM|PM)?))\s*#)</string>
			<key>name</key>
			<string>string.quoted.double.vbnet</string>
		</dict>
		<key>floating-point-literal</key>
		<dict>
			<key>comment</key>
			<string>floating-point literals</string>
			<key>match</key>
			<string>(?i:[0-9]*(\.[0-9]+)?((?&lt;=[0-9])E[+-]?[0-9]+)?(?&lt;=[0-9])[FRD@&amp;#]?)</string>
			<key>name</key>
			<string>string.quoted.double.vbnet</string>
		</dict>
		<key>identifier</key>
		<dict>
			<key>comment</key>
			<string>identifiers</string>
			<key>match</key>
			<string>(([\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}]|_[_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Nd}\p{Mn}\p{Mc}\p{Cf}\p{Pc}])[_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Nd}\p{Mn}\p{Mc}\p{Cf}\p{Pc}]*[%&amp;@!#$]?|\[([\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}]|_[_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Nd}\p{Mn}\p{Mc}\p{Cf}\p{Pc}])[_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Nd}\p{Mn}\p{Mc}\p{Cf}\p{Pc}]*\])</string>
			<key>name</key>
			<string>variable.other.namespace-alias.vbnet</string>
		</dict>
		<key>integer-literal</key>
		<dict>
			<key>comment</key>
			<string>integer literals</string>
			<key>match</key>
			<string>(?i)(&amp;H[0-9A-F]+|&amp;O[0-7]+|&amp;B[0-1]+|[0-9]+)(S|I|L|US|UI|UL|%|!)?</string>
			<key>name</key>
			<string>string.quoted.double.vbnet</string>
		</dict>
		<key>keyword-a</key>
		<dict>
			<key>comment</key>
			<string>keywords A</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(AddHandler|AddressOf|Aggregate|Alias|And|AndAlso|Ansi|As|Ascending|Assembly|Async(?=\s+(Sub|Function))|Auto|Await)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-b</key>
		<dict>
			<key>comment</key>
			<string>keywords B</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])((?&lt;=Compare)\s+Binary|Boolean|ByRef|Byte|ByVal)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-c</key>
		<dict>
			<key>comment</key>
			<string>keywords C</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|(?&lt;=Option\s)Compare|Const|Continue|CShort|CSng|CStr|CType|Custom(?=\s+Event))\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-d</key>
		<dict>
			<key>comment</key>
			<string>keywords D</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Date|Decimal|Declare|Default|Delegate|Descending|Dim|DirectCast|Distinct|Do|Double)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-e</key>
		<dict>
			<key>comment</key>
			<string>keywords E</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Each|Else|ElseIf|End|EndIf|Enum|Equals|Erase|Error|Event|Exit|(?&lt;=Option)\s+Explicit)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-f</key>
		<dict>
			<key>comment</key>
			<string>keywords F</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(False|Finally|For|Friend|From(?=\s+{)|From|Function)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-g</key>
		<dict>
			<key>comment</key>
			<string>keywords G</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Get|GetType|Global|GoSub|GoTo|Group\s+By|Group)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-h</key>
		<dict>
			<key>comment</key>
			<string>keywords H</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Handles)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-i</key>
		<dict>
			<key>comment</key>
			<string>keywords I</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(If|Implements|Imports|In|(?&lt;=Option)\s+Infer|Inherits|Integer|Interface|Into|Is|IsNot|Iterator(?=\s+(Function|Property)))\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-j</key>
		<dict>
			<key>comment</key>
			<string>keywords J</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Join)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-k</key>
		<dict>
			<key>comment</key>
			<string>keywords K</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Key)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-l</key>
		<dict>
			<key>comment</key>
			<string>keywords L</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Let|Lib|Like|Long|Loop)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-m</key>
		<dict>
			<key>comment</key>
			<string>keywords M</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-n</key>
		<dict>
			<key>comment</key>
			<string>keywords N</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(NameOf|Namespace|Narrowing|New|Next|Not|Nothing|NotInheritable|NotOverridable)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-o</key>
		<dict>
			<key>comment</key>
			<string>keywords</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Object|Of|(?&lt;=Explicit|Infer|Strict)\s+Off|On|Operator|Option|Optional|Or|Order\s+By|OrElse|Out|Overloads|Overridable|Overrides)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-p</key>
		<dict>
			<key>comment</key>
			<string>keywords P</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(ParamArray|Partial(?=\s+(Class|Structure|Module|Interface))|Partial(?=\s+(Class|Structure|Module|Interface|Sub|Public|Private|Protected|Friend|MustInherit|NotInheritable|NotOverrideable|Overridable|Shared))|Preserve|Private|Property|Protected|Public)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-r</key>
		<dict>
			<key>comment</key>
			<string>keywords R</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(RaiseEvent|ReadOnly|ReDim|(?&lt;=#|#End\s)Region|RemoveHandler|Resume|Return)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-s</key>
		<dict>
			<key>comment</key>
			<string>keywords S</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Select|Set|Shadows|Shared|Short|Single|Skip|Static|Step|Stop|(?&lt;=Option)\s+Strict|String|Structure|Sub|SyncLock)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-t</key>
		<dict>
			<key>comment</key>
			<string>keywords T</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Take|(?&lt;=Compare)\s+Text|Then|Throw|To|True|Try|TryCast|TypeOf)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-u</key>
		<dict>
			<key>comment</key>
			<string>keywords U</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Unicode|Until|Using)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-v</key>
		<dict>
			<key>comment</key>
			<string>keywords B</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Variant)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-w</key>
		<dict>
			<key>comment</key>
			<string>keywords W</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Wend|When|Where|While|Widening|With|WithEvents|WriteOnly)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-x</key>
		<dict>
			<key>comment</key>
			<string>keywords X</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Xor)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>keyword-y</key>
		<dict>
			<key>comment</key>
			<string>keywords Y</string>
			<key>match</key>
			<string>(?i)(?&lt;![.!])(Yield)\b</string>
			<key>name</key>
			<string>keyword.other.vbnet</string>
		</dict>
		<key>string-literal</key>
		<dict>
			<key>comment</key>
			<string>string literals</string>
			<key>match</key>
			<string>(["\x{201C}\x{201D}]([^"\x{201C}\x{201D}]|["\x{201C}\x{201D}]{2})*["\x{201C}\x{201D}])</string>
			<key>name</key>
			<string>string.quoted.double.vbnet</string>
		</dict>
		<key>symbol</key>
		<dict>
			<key>comment</key>
			<string>symbols</string>
			<key>match</key>
			<string>(([&amp;*+\-/\\^&lt;=&gt;])|([(){}!#,.:]|((?&lt;= )_(?=\s$)))|\?)</string>
			<key>name</key>
			<string>variable.other.namespace-alias.vbnet</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.vbnet</string>
	<key>uuid</key>
	<string>975d5447-0eb5-444c-a471-5934193ca1ea</string>
</dict>
</plist>
